### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by joss-me** [Joel2B/XVideos-PornHub-RedTube-API#5]
I tried uploading [dir](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/blob/main/src) to my website, but it's just a blank page

**Comment by Joel2B** [comment]
doing this doesn't show anything?
`https://{YOUR_DOMAIN}/{YOUR_PATH}/?site_id=xvideos&video_id=59934029`

example
https://appsdev.cyou/xv-ph-rt/api/?site_id=xvideos&video_id=59934029

check if you have any error_log file and send its content here, please.

**Comment by Joel2B** [comment]
if failure again, open a new issue
