### ISSUE TITLE
api-your-own-servers giving 500 error

### ISSUE THREAD

**Issue by Superion03** [Joel2B/XVideos-PornHub-RedTube-API#6]
Hi there,

The api-your-own-servers script isnt working anymore, when I check the error logs, this is what I see:

```PHP Fatal error:  Uncaught <table style="border: 1px" cellspacing="0">
<tr><td colspan="3" style="background: #ff9999"> <b>HTTP_Request2_LogicException</b>: Invalid cookie: '&lt;!doctype html&gt;
&lt;html&gt;
 &lt;head&gt;
&lt;meta charset=&quot;utf-8&quot;&gt;
 &lt;meta name' in <b>/home/server1234/public_html/api/api-for-own-servers/server.php</b> on line <b>76</b></td></tr>
<tr><td colspan="3" style="background-color: #aaaaaa; text-align: center; font-weight: bold;">Exception trace</td></tr>
<tr><td style="text-align: center; background: #cccccc; width:20px; font-weight: bold;">#</td><td style="text-align: center; background: #cccccc; font-weight: bold;">Function</td><td style="text-align: center; background: #cccccc; font-weight: bold;">Location</td></tr>
<tr><td style="text-align: center;">0</td><td>HTTP_Request2->addCookie()</td><td>/home/server1234/public_html/api/api-for-own-servers/server.php:76</td></tr>
 <tr><td style="text-align: center;">1</td><td>Server->set_cookie_bypass()</td><td>/home/server1234 in /home/server1234/public_html/api/api-for-own-servers/HTTP/Request2.php on line 558

```

any idea?

**Comment by Joel2B** [comment]
hello

still not working?

i think that when the api to get the cookie is down, everything stops working

i could validate that part or publish in github the api 
https://tmp02.appsdev.cyou/bypass-js-check,
so that anyone can use it and not depend on this server

**Comment by Superion03** [comment]
Hi,

Still getting 500 error, can you share the API of the bypass-js-check so we can depend on our bypass-js-check api.. Another question what are the requirments for your script, because if i run your scrip local on my machine then the script works correctly..

**Comment by Joel2B** [comment]
i will publish the api very soon

i use the following configuration:

![1](https://user-images.githubusercontent.com/58922368/161360241-653ba0da-4648-486f-a87e-2941cb4da922.jpg)

check if your server is receiving the cookie data
https://tmp02.appsdev.cyou/bypass-js-check/?url=https://www.pornhub.com/view_video.php?viewkey=ph6116a13a48187

should return
`RNKEY=1609109*1964531:1072726575:462085776:1`

**Comment by Superion03** [comment]
Nope, unfortunately the server doesn't return any cookie data

**Comment by Joel2B** [comment]
try now, i just excluded it from cloudflare firewall, send what you get with 
`curl -i https://tmp02.appsdev.cyou/bypass-js-check/?url=https://es.pornhub.com/view_video.php?viewkey=ph6116a13a48187`

**Comment by Superion03** [comment]
I use indeed Cloudflare nameservers to connect my domain to the server and for using their certificate. Here the output of the curl

```
curl -i https://{myDomain}.com/api/src/bypass-js-check/?url=https://es.pornhub.com/view_video.php?viewkey=ph6116a13a48187
HTTP/2 200 
date: Fri, 08 Apr 2022 06:59:53 GMT
content-type: application/json
content-length: 0
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=5rTvJPs8ROLi44kGSZV318%2F9rHnyXbEk30%2FdAUQVKQegX%2Bb9%2FVTfnQMfDmiGexqbX1Tazk3Gq16DDvTN3RpCvmYej9rxqvNCitsSPx7am1SmuceTK1xJRg5OeKkRK5nSiud2mcD1Ns%2FeISQFkJ8R8rKOxA%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 6f891f7468659ba4-FRA
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

**Comment by Joel2B** [comment]
try to run exactly this command in the terminal of your server, 
to see if responds something, 
and to know if is not blocked by my cloudflare

`curl -i https://tmp02.appsdev.cyou/bypass-js-check/?url=https://www.pornhub.com/view_video.php?viewkey=ph6116a13a48187`

should show you something like this

![image](https://user-images.githubusercontent.com/58922368/162404109-957d95bf-67a2-4553-ab6a-303458e19f56.png)

i still don't publish the api "bypass-js-check" so you can only use it from the api 
`https://tmp02.appsdev.cyou/bypass-js-check/?url={url}`

**Comment by Superion03** [comment]
Ahh oke, this is my response of the curl:


```
ubuntu@vps:~$ curl -i https://tmp02.appsdev.cyou/bypass-js-check/?url=https://www.pornhub.com/view_video.php?viewkey=ph6116a13a48187
HTTP/2 200 
date: Fri, 08 Apr 2022 10:27:34 GMT
content-type: text/html
last-modified: Friday, 08-Apr-2022 10:27:34 GMT
cache-control: private, no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0, s-maxage=0
cf-edge-cache: no-cache
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=Pa962T0DlSGM6JlnKC9ALG4Vah0d14FF01oWh3yCvAFQ5qqKMeXZaZWNsY%2Bp4IajLyoulkbbYryRWn4mP47K0e7xzrS6gtmQ145F5qngW5kGkHrKWtcPy28mqENf2mwcClOwSBKC6qCoLYcJTnoCcb0%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 6f8a4fab6a6e9b40-FRA
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="robots" content="noindex, nofollow">
<title>One moment, please...</title>
<style>
body {
    background: #F6F7F8;
    color: #303131;
    font-family: sans-serif;
    margin-top: 45vh;
    text-align: center;
}
</style>
</head>
<body>
<h1>Please wait while your request is being verified...</h1>
<form id="wsidchk-form" style="display:none;" action="/z0f76a1d14fd21a8fb5fd0d03e0fdc3d3cedae52f" method="get">
<input type="hidden" id="wsidchk" name="wsidchk"/>
</form>
<script>
(function(){
    var west=+((+!+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+[])+(+!+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+!+[]+!![]+!![]+!![]+!![]+[])+(+![])+(+!+[]+!![]+[])),
        east=+((+!+[])+(+!+[]+!![]+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+![]+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!+[]+!![]+!![]+!![]+!![]+!![])+(+!+[]+!![]+!![]+!![]+!![]+[])),
        x=function(){try{return !!window.addEventListener;}catch(e){return !!0;} },
        y=function(y,z){x() ? document.addEventListener("DOMContentLoaded",y,z) : document.attachEvent("onreadystatechange",y);};
    y(function(){
        document.getElementById('wsidchk').value = west + east;
        document.getElementById('wsidchk-form').submit();
    }, false);
})();
</script>
</body>
```

**Comment by Joel2B** [comment]
try again, i made some changes in cf and hosting, if doesn't work, 
so i think the problem is partly with the hosting and i cannot do much about it

the only thing left is to use your own api "bypass-js-check", 
i will publish it in a few days

**Comment by khaled-elbehery** [comment]
For me the XVideos-PornHub-RedTube-API I linked with the video-player-wordpress-plugin and it works very well.
Basically I use videos from xvideos and it works without a problem.
When you posted this problem, I tried pornhub and found that it only brings the thumbnail and does not bring the video playback link.
I tested it now and found that it brings the links as follows.

https://domain.com/api/src/?site_id=pornhub&video_id=ph610e18c5d3dfc 

`{"hls":{"all":"https:\/\/dv-h.phncdn.com\/hls\/videos\/202108\/07\/392536891\/,1080P_4000K,720P_4000K,480P_2000K,240P_1000K,_392536891.mp4.urlset\/master.m3u8?ttl=1649456743&l=0&ipa=185.37.231.112&hash=3a0930c0a32c3ff29c82caec07099e64","1080p":"https:\/\/dv-h.phncdn.com\/hls\/videos\/202108\/07\/392536891\/1080P_8000K_392536891.mp4\/master.m3u8?ttl=1649456743&l=0&ipa=185.37.231.112&hash=147adc4c657cb68b2e12f5fefba7e52a","720p":"https:\/\/dv-h.phncdn.com\/hls\/videos\/202108\/07\/392536891\/720P_4000K_392536891.mp4\/master.m3u8?ttl=1649456743&l=0&ipa=185.37.231.112&hash=c69313bddc91e93e66f4116b199e65c5","480p":"https:\/\/dv-h.phncdn.com\/hls\/videos\/202108\/07\/392536891\/480P_2000K_392536891.mp4\/master.m3u8?ttl=1649456743&l=0&ipa=185.37.231.112&hash=abe6c1eca3524595f8ac4bf55113aaed","240p":"https:\/\/dv-h.phncdn.com\/hls\/videos\/202108\/07\/392536891\/240P_1000K_392536891.mp4\/master.m3u8?ttl=1649456743&l=0&ipa=185.37.231.112&hash=65698a556079758b6b8b81a126d35dda"},"mp4":{"1080p":"https:\/\/ev.phncdn.com\/videos\/202108\/07\/392536891\/1080P_8000K_392536891.mp4?validfrom=1649449544&validto=1649456744&rate=500k&burst=1200k&ipa=185.37.231.112&hash=W7jgd953IdZM8V5Brwh6myAXicM%3D","720p":"https:\/\/ev.phncdn.com\/videos\/202108\/07\/392536891\/720P_4000K_392536891.mp4?validfrom=1649449544&validto=1649456744&rate=500k&burst=1200k&ipa=185.37.231.112&hash=YhtkNVG%2FZIhKYE7O7UjApbCg2UY%3D","480p":"https:\/\/ev.phncdn.com\/videos\/202108\/07\/392536891\/480P_2000K_392536891.mp4?validfrom=1649449544&validto=1649456744&rate=500k&burst=1200k&ipa=185.37.231.112&hash=cja8mLQ6bBo7vORG7x5PQNHD5CM%3D","240p":"https:\/\/ev.phncdn.com\/videos\/202108\/07\/392536891\/240P_1000K_392536891.mp4?validfrom=1649449544&validto=1649456744&rate=500k&burst=1200k&ipa=185.37.231.112&hash=LTJYtJItOivcm%2FqeGukMNC71MlM%3D"},"thumb":"https:\/\/di.phncdn.com\/videos\/202108\/07\/392536891\/original\/(m=q10T9WWbeaAaGwObaaaa)(mh=KBskdYKwbO5-FSvP)0.jpg","thumbnails":"https:\/\/domain.com\/api\/src\/vtt\/cG9ybmh1YnBwcHBwcHBwcNkebokmJ3opWJRN8uRhSh6kxNYNTMA79Lu-L3H82Nmuf2pC5LF1OYtD5r0AmtYVbPoguygkv-eyd-5eQ8f6y2fzW8RRu1-R3W-qHxNCLtAFqwPwe3ffR-UVjHsEGLdtHHp6akfUpsFKbYNVhSaGjrrhfwaAWd_cQhtN00ijB0cqTLo_IdCU-GUYS2rIFOr1TgXCAXKqTCwQ27SD63DMmBIaYEUG2btK9oB5vP7jMlP9RqsjMzudM7hMZDj-f2B1A4_f2LN8Z9IP7MJRggNc4976jrrlDJFqSAdt6WQfgCK2T69EpU8FVaWyORRf93OAuyfBJBjo40nhHoiSKiFG1n-EJZjno93NMpjjxbgS9CmL"}`

But inside wordpress-post the thumbnail appears but the video is not working.

iframe view-source

`<video id="video-player" poster="https://di.phncdn.com/videos/201807/31/176704481/original/(m=eaAaGwObaaaa)(mh=MCloAr0CWH3pexGb)15.jpg"><source src="https://ev-h.phncdn.com/hls/videos/201807/31/176704481/,180807_0336_720P_4000K,180807_0336_480P_2000K,180807_0336_240P_1000K,_176704481.mp4.urlset/master.m3u8?validfrom=1649449031&amp;validto=1649456231&amp;ipa=185.37.231.112&amp;hdl=-1&amp;hash=jjMHnws0QqjvStaMEY%2BvUegwW3g%3D" type="application/x-mpegURL" title="all"></source></video>`
 

But in this debug.php link I found the video working 
https://domain.com/api/src/debug.php?site_id=pornhub 

```
missing_data
array(13) {
  [0]=>
  string(3) "all"
  [1]=>
  string(5) "1080p"
  [2]=>
  string(4) "720p"
  [3]=>
  string(4) "480p"
  [4]=>
  string(4) "240p"
  [5]=>
  string(5) "1080p"
  [6]=>
  string(4) "720p"
  [7]=>
  string(4) "480p"
  [8]=>
  string(4) "240p"
  [9]=>
  string(8) "duration"
  [10]=>
  string(5) "thumb"
  [11]=>
  string(10) "thumbnails"
  [12]=>
  string(18) "sampling_frequency"
}
Msg: 1
Category: 0 - primary
URL
https://tmp01.appsdev.cyou/?url=https%3A%2F%2Fwww.pornhub.com%2Fview_video.php%3Fviewkey%3Dph6116a13a48187&cookie_action=write&cookie_id=pornhub
1.57s gmu
1.05s hls
0.55s mp4
1.60s lc
missing_data
array(0) {
}
3.17s total load
Msg: 2
array(4) {
  ["hls"]=>
  array(5) {
    ["all"]=>
    string(210) "https://dv-h.phncdn.com/hls/videos/202108/13/392894661/,1080P_4000K,720P_4000K,480P_2000K,240P_1000K,_392894661.mp4.urlset/master.m3u8?ttl=1649459378&l=0&ipa=185.37.231.112&hash=4b2ad9d6d1df1ea3c0b9662bf6069054"
    ["1080p"]=>
    string(168) "https://dv-h.phncdn.com/hls/videos/202108/13/392894661/1080P_8000K_392894661.mp4/master.m3u8?ttl=1649459378&l=0&ipa=185.37.231.112&hash=8c359dc170146c7ff30a65537bfea878"
    ["720p"]=>
    string(167) "https://dv-h.phncdn.com/hls/videos/202108/13/392894661/720P_4000K_392894661.mp4/master.m3u8?ttl=1649459378&l=0&ipa=185.37.231.112&hash=6e6be0075cbdfb75b79703a042c23c3e"
    ["480p"]=>
    string(167) "https://dv-h.phncdn.com/hls/videos/202108/13/392894661/480P_2000K_392894661.mp4/master.m3u8?ttl=1649459378&l=0&ipa=185.37.231.112&hash=b99ddb9ec67e5fb24cdf877df4efb769"
    ["240p"]=>
    string(167) "https://dv-h.phncdn.com/hls/videos/202108/13/392894661/240P_1000K_392894661.mp4/master.m3u8?ttl=1649459378&l=0&ipa=185.37.231.112&hash=bce198fb45ff021d566d84100cef17db"
  }
  ["mp4"]=>
  array(4) {
    ["1080p"]=>
    string(193) "https://ev.phncdn.com/videos/202108/13/392894661/1080P_8000K_392894661.mp4?validfrom=1649452179&validto=1649459379&rate=500k&burst=1400k&ipa=185.37.231.112&hash=D4SWsEjwUVj%2BYcpjvVvP4ZYYJu4%3D"
    ["720p"]=>
    string(192) "https://ev.phncdn.com/videos/202108/13/392894661/720P_4000K_392894661.mp4?validfrom=1649452179&validto=1649459379&rate=500k&burst=1400k&ipa=185.37.231.112&hash=9Y3Au%2FzJBQYFHbXxyH7MnQ3yFRo%3D"
    ["480p"]=>
    string(198) "https://ev.phncdn.com/videos/202108/13/392894661/480P_2000K_392894661.mp4?validfrom=1649452179&validto=1649459379&rate=500k&burst=1400k&ipa=185.37.231.112&hash=OpiC1mOT7n%2FduoKm%2Fn1%2Bii1%2FrDk%3D"
    ["240p"]=>
    string(190) "https://ev.phncdn.com/videos/202108/13/392894661/240P_1000K_392894661.mp4?validfrom=1649452179&validto=1649459379&rate=500k&burst=1400k&ipa=185.37.231.112&hash=Jqkm8xLOoGlc9J614iwgx3PnFes%3D"
  }
  ["thumb"]=>
  string(108) "https://ei.phncdn.com/videos/202108/13/392894661/original/(m=q3K9ZXWbeaAaGwObaaaa)(mh=DDjxUSnldtA2fkvP)0.jpg"
  ["thumbnails"]=>
  string(414) "https://domain.com/api/src/vtt/cG9ybmh1YnBwcHBwcHBwcNkebokmJ3opWJRN8uRhSh4SiemWQYmsvkbqoqqzDCzTLIgslfky9M9krTRgBrVV97enBCdKXzA4wIVK4gGnPMAwko-Zrx1qYhDXUFJRd4GOGy8dzZY-c_N9KFTvdUpsd-jbxAav9Sbt8ZMxKg8kZufXu4-2r_trqtXTDJUsCnIbq17hqR2x4f7HNFKLfT8kQW0wzLaz6nV64GKAi_cpsO_r_kT5vgzRw_yWekouHxtGbksvIeKVst_Xi_9d1VYjlSuT81dAvukuz8YbVp8VJkfppg946_MtsdzPEi3zpmYXMeEZP6TSU-_VFDZPKeLoMLtwUfZO6All_zv-uKZ4fDFKqL0wbl36DhT7ibpFEE4Y"
}
memory usage
2MiB
```

**Comment by Joel2B** [comment]
> When you posted this problem, I tried pornhub and found that it only brings the thumbnail and does not bring the video playback link.

to be honest, i didn't test pornhub/redtube in the plugin, my mistake,
in the case of pornhub, with what you sent, it seems to get the m3u8 links, which are under CORS,
so it would not work, and you would have to use the mp4 links instead,
would be necessary to change the plugin logic to make it do that.

with redtube, there is no cors, so i think it would work.

i still need to publish a lot of code and document it, so that everyone can see the problems/solutions that i have stumbled upon.

**Comment by Superion03** [comment]
> try again, i made some changes in cf and hosting, if doesn't work, so i think the problem is partly with the hosting and i cannot do much about it
> 
> the only thing left is to use your own api "bypass-js-check", i will publish it in a few days

Still the same :(, its strange that i dont get any problem if i use my laptop as a server. But when i use a VPS(from ovh.com) then it doesnt work..

**Comment by Superion03** [comment]
> try again, i made some changes in cf and hosting, if doesn't work, so i think the problem is partly with my hosting and i cannot do much about it
> 
> the only thing left is to use your own api "bypass-js-check", i will publish it in a few days

Any update when you will publish the "bypass-js-check" api?

**Comment by Joel2B** [comment]
> Any update when you will publish the "bypass-js-check" api?

still using this script?
could you tell if there is any problem with the js verification? 
i recently returned to this project, and for the moment i haven't seen this problem

**Comment by Superion03** [comment]
> > Any update when you will publish the "bypass-js-check" api?
> 
> still using this script? could you tell if there is any problem with the js verification? i recently returned to this project, and for the moment i haven't seen this problem

Yes still using, because everything works great with xvideos. But with pornhub the js verification doesnt work

**Comment by Joel2B** [comment]
> Yes still using, because everything works great with xvideos. But with pornhub the js verification doesnt work

could you send a sample of that js verification?

i made a new bypass, i want to test if works, 
because i don't get the verification anymore,

if what i did works, i will post it for you to test.

**Comment by SylberG** [comment]
> > Yes still using, because everything works great with xvideos. But with pornhub the js verification doesnt work
> 
> could you send a sample of that js verification?
> 
> i made a new bypass, i want to test if works, because i don't get the verification anymore,
> 
> if what i did works, i will post it for you to test.

I just used your js verification api from your previous branche

**Comment by Superion03** [comment]
> > Yes still using, because everything works great with xvideos. But with pornhub the js verification doesnt work
> 
> could you send a sample of that js verification?
> 
> i made a new bypass, i want to test if works, because i don't get the verification anymore,
> 
> if what i did works, i will post it for you to test.

I just used your js verification api from your previous branche

**Comment by Superion03** [comment]
i think it has to do with my VPS, i dont know why my server doesnt receive any cookie data.. Ive tried it on an another webhosting and there it works correctly

**Comment by Joel2B** [comment]
@Superion03 

i just published the code that i use to bypass the js verification of pornhub.

[bypass-js-check](https://github.com/Joel2B/bypass-js-check)

place it on the same server as the application you are using to make the requests,
and change the `BYPASS_URL` url of the `config.php` to yours.
